version: '3'
services:
  smokeping:
    build:
      context: .
      dockerfile: Dockerfile
    image: asdjkm1234/smokeping-master:latest
    ports:
      - "8080:80"
    volumes:
      - ./smokeping_config:/usr/local/smokeping/etc
    container_name: smokeping-master
    environment:
      - TZ=Asia/Shanghai
